before_all do |lane, options|
  if options[:queue]
    queue(
      lane: lane.to_s,
      lane_parameters: options
    )
    UI.abort_with_message! "We queued this so not running"
  end
end

lane :test1 do
  UI.message "Starting test1..."
  sleep 30
  UI.message "Ending test1..."
end

lane :test2 do
  UI.message "Starting test2..."
  sleep 30
  UI.message "Ending test2..."
end

lane :fail do
  UI.message "Starting fail..."
  sleep 30
  raise "Whoops"
end

platform :ios do
  lane :test1 do
    UI.message "Starting ios test1..."
    sleep 30
    UI.message "Ending ios test1..."
  end

  lane :ios_only do
    UI.message "Starting ios ios_only..."
    sleep 30
    UI.message "Ending ios ios_only..."
  end
end

platform :android do
  lane :test1 do
    UI.message "Starting android test1..."
    sleep 30
    UI.message "Ending android test1..."
  end

  lane :android do
    UI.message "Starting android android..."
    sleep 30
    UI.message "Ending android android..."
  end
end
